# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-16 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JdBrand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品品牌ID')),
                ('brand_name', models.CharField(max_length=64, verbose_name='商品品牌名称')),
                ('third_cate_id', models.ForeignKey(db_column='third_cate_id', on_delete=django.db.models.deletion.CASCADE, to='main.JdThirdCate')),
            ],
            options={
                'verbose_name': '商品品牌',
                'verbose_name_plural': '商品品牌',
                'db_table': 'jd_brand',
            },
        ),
    ]
