# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-01-25 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jdbrand',
            table='jd_brand',
        ),
    ]
