# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-16 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False, verbose_name='购物车ID')),
                ('number', models.IntegerField(verbose_name='购物数量')),
                ('uid', models.IntegerField(verbose_name='用户ID')),
                ('shop_id', models.IntegerField(verbose_name='商品ID')),
                ('is_valid', models.BooleanField(default=1)),
                ('is_delete', models.BooleanField(default=1)),
            ],
            options={
                'verbose_name': '购物车信息',
                'verbose_name_plural': '购物车信息',
                'db_table': 'Jd_ShopCart',
            },
        ),
    ]
