# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-11 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('shop_id', models.IntegerField()),
                ('is_valid', models.BooleanField(default=1)),
                ('is_delete', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'Jd_ShopCart',
            },
        ),
    ]
