# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-12 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopcart', '0002_auto_20190212_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='shop_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
