# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-15 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('order_code', models.CharField(max_length=128)),
                ('uid', models.IntegerField()),
                ('total_money', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
