# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-14 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('order_code', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('pay_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
