# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-17 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='shop_name',
            field=models.CharField(max_length=256),
        ),
    ]
