# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-17 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190217_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
