# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-17 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20190217_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
    ]
