# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-14 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('username', models.CharField(max_length=16, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.CharField(max_length=64, unique=True, verbose_name='邮箱地址')),
                ('active', models.BooleanField(default=0, verbose_name='活跃状态')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
    ]
