# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-16 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JdShop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('title', models.CharField(max_length=80, verbose_name='商品名称')),
                ('original_price', models.IntegerField(verbose_name='商品原价')),
                ('promote_price', models.IntegerField(verbose_name='商品促销价')),
                ('img_url', models.CharField(max_length=256, verbose_name='商品图片地址')),
                ('month_sales', models.IntegerField(verbose_name='商品月销量')),
                ('total_sales', models.IntegerField(verbose_name='商品总销量')),
                ('stock', models.IntegerField(verbose_name='商品点击量')),
                ('total_evaluates', models.IntegerField(verbose_name='商品评论数')),
                ('brand_name', models.CharField(default='', max_length=64, verbose_name='商品品牌')),
                ('third_cate_id', models.ForeignKey(db_column='third_cate_id', on_delete=django.db.models.deletion.CASCADE, to='main.JdThirdCate')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
                'db_table': 'jd_shop',
            },
        ),
    ]
