# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-16 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JdFirstCate',
            fields=[
                ('first_cate_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_cate_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Jd_FirstCate',
            },
        ),
        migrations.CreateModel(
            name='JdSecondCate',
            fields=[
                ('second_cate_id', models.AutoField(primary_key=True, serialize=False)),
                ('second_cate_name', models.CharField(max_length=200)),
                ('first_cate_id', models.ForeignKey(db_column='first_cate_id', on_delete=django.db.models.deletion.CASCADE, to='main.JdFirstCate')),
            ],
            options={
                'db_table': 'Jd_SecondCate',
            },
        ),
        migrations.CreateModel(
            name='JdThirdCate',
            fields=[
                ('third_cate_id', models.AutoField(primary_key=True, serialize=False)),
                ('third_cate_name', models.CharField(max_length=200)),
                ('second_cate_id', models.ForeignKey(db_column='second_cate_id', on_delete=django.db.models.deletion.CASCADE, to='main.JdSecondCate')),
            ],
            options={
                'db_table': 'Jd_ThirdCate',
            },
        ),
    ]
